version: "3"

volumes:
  emqx_data:
    name: emqx_data

services:
  # MQTT broker
  emqx:
    image: emqx:5.1
    container_name: stair_challenge_emqx
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      - backend
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - $PWD/emqx_data:/opt/emqx/data

networks:
  backend: