[tool.poetry]
name = "stair-flask"
version = "0.1.0"
description = "Management environment of the stair challenge project"
authors = ["Klaas Schoute <hello@student-techlife.com>"]
maintainers = ["Klaas Schoute <hello@student-techlife.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.3"
paho-mqtt = "^1.6.1"
rpi-ws281x = "^5.0.0"
python-dotenv = "^1.0.0"
flask-sqlalchemy = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
